### PR TITLE
Feature price

### PR DESCRIPTION
**Pull request by rsanchez-dv**
Adding Price Controller, Service, Model, DAT and one test.

### CODE REVIEW

**Review by neveland98 — COMMENTED** [review]
Why is there a separate table for prices? Couldn't that just be an attribute of the Listing model?

**Review by jaitken — APPROVED** [review]
Looks good!

**Comment by jaitken** [comment]
Nathanial is probably correct about just having the price on the listing model if it is just going to be a set float, wouldn't need to do separate testing that way too

**Comment by rsanchez-dv** [comment]
K, I've updated the logic. Its now with the listing model.

**Review by neveland98 — APPROVED** [review]

**Pull request merged**
